version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  mysql:
    image: mysql:8.0.25
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"