DROP TABLE IF EXISTS `test`;
CREATE TABLE IF NOT EXISTS `test`
(
    `id`   int(40)     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(11) NOT NULL
) ENGINE = innodb,
  DEFAULT CHARSET = utf8;